env: dev
serviceip: 0.0.0.0
serviceport: 5000
loglevel: debug
database: 
  driver: mysql
  user: root
  password: root
  host: 192.168.1.20
  port: 3306
  dbname: invite
  charset: utf8mb4
passport: 
  endpoint: http://passport.example.com
  secretid: secret_id1
  secretkey: secret_key1