- name: Add user "{{ username }}"
  user:
    name: "{{ username }}"
    shell: "/bin/bash"
  when: username is defined and username != ""
#    password: "{{ adduser_password | default(omit)}}"
#    update_password: "{{ adduser_password_update }}"
#    comment: "{{ adduser_user_comments | default(omit) }}"
#    shell: "{{ adduser_shell | default('/bin/bash') }}"
#    expires: "{{ adduser_expires | default(omit) }}"

- name: Add authorized keys for {{ username }} user
  authorized_key:
    user: "{{ username }}"
    key: "{{ item }}"
  with_file: "{{ public_keys }}"
  when: public_keys is defined and public_keys != "" and adduser_sshkey_options is not defined
  become: yes
